### ISSUE TITLE
Enhancement requested

### ISSUE THREAD

**Issue by k-atb** [USDA-ARS-NWRC/awsm#22]
When iSnobal is updated with ASO data can we please auto-generate a report that documents the changes made i.e. where snow is added, removed, where SWE is added, removed

**Comment by micah-prime** [comment]
We have implemented the auto updating in AWSM and are in the midst of testing it. When that is finished I will make sure to pass the summary statistics about the changes from the update to our auto reporting software, SNOWAV so that it can be included in that report. We'll keep you in the loop!

-Micah S.

**Comment by micah-prime** [comment]
This functionality is in SNOWAV (https://github.com/USDA-ARS-NWRC/SNOWAV) and the updating in AWSM is going into our next version bump (this week I hope!).
